apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: us.gcr.io/ticketing-399717/payment
          env:
            - name: CLUSTER_ID
              value: ticketing
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-keys
                  key: JWT_KEY
            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-keys
                  key: STRIPE_KEY
            - name: CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MONGO_URI
              value: mongodb://payment-mongo-srv:27017/payment
            - name: NATS_URI
              value: http://nats-srv:4222
---
apiVersion: v1
kind: Service
metadata:
  name: payment-srv
spec:
  selector:
    app: payment
  ports:
    - name: payment
      protocol: TCP
      port: 3000
      targetPort: 3000
